"""catchup_missing_columns

Revision ID: 11ccc184c1b7
Revises: a85d023bac6e
Create Date: 2026-07-19 14:37:55.671724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ccc184c1b7'
down_revision: Union[str, Sequence[str], None] = 'a85d023bac6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    notification_type_enum = postgresql.ENUM('SESSION_CREATED', 'SESSION_UPDATED', 'SESSION_COMPLETED', 'SUMMARY_READY', 'QUIZ_READY', 'FLASHCARDS_READY', 'MEMBER_JOINED', 'MEMBER_LEFT', 'MEETING_LINK_ADDED', 'RESOURCE_UPLOADED', 'RESOURCE_DELETED', 'AI_SESSION_CREATED', 'AI_STUDY_PLAN_READY', 'GROUP_CREATED', 'GROUP_DELETED', name='notificationtype', create_type=False)
    notification_type_enum.create(op.get_bind(), checkfirst=True)
    
    flashcard_deck_status_enum = postgresql.ENUM('PENDING', 'GENERATING', 'READY', 'FAILED', name='flashcarddeckstatus', create_type=False)
    flashcard_deck_status_enum.create(op.get_bind(), checkfirst=True)
    
    flashcard_progress_status_enum = postgresql.ENUM('NEW', 'LEARNING', 'MASTERED', name='flashcardprogressstatus', create_type=False)
    flashcard_progress_status_enum.create(op.get_bind(), checkfirst=True)
    
    meeting_type_enum = postgresql.ENUM('NONE', 'GOOGLE_MEET', 'ZOOM', 'MICROSOFT_TEAMS', 'DISCORD', 'OTHER', name='meetingtype', create_type=False)
    meeting_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', notification_type_enum, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('flashcard_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', flashcard_deck_status_enum, nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_flashcard_decks_id'), 'flashcard_decks', ['id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.create_table('flashcard_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('status', flashcard_progress_status_enum, nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_progress_id'), 'flashcard_progress', ['id'], unique=False)
    op.drop_constraint('group_members_group_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'study_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.add_column('study_sessions', sa.Column('meeting_type', meeting_type_enum, nullable=False))
    op.add_column('study_sessions', sa.Column('meeting_url', sa.String(length=512), nullable=True))
    op.add_column('study_sessions', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('study_sessions', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('study_sessions', sa.Column('generated_by', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS notificationtype")
    op.execute("DROP TYPE IF EXISTS flashcarddeckstatus")
    op.execute("DROP TYPE IF EXISTS flashcardprogressstatus")
    op.execute("DROP TYPE IF EXISTS meetingtype")

    op.drop_column('study_sessions', 'generated_by')
    op.drop_column('study_sessions', 'end_time')
    op.drop_column('study_sessions', 'start_time')
    op.drop_column('study_sessions', 'meeting_url')
    op.drop_column('study_sessions', 'meeting_type')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_group_id_fkey', 'group_members', 'study_groups', ['group_id'], ['id'])
    op.drop_index(op.f('ix_flashcard_progress_id'), table_name='flashcard_progress')
    op.drop_table('flashcard_progress')
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_flashcard_decks_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
