"""add structured session columns

Revision ID: 661ad5a26d29
Revises: 5f9e82de5e15
Create Date: 2026-07-15 16:10:26.264572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '661ad5a26d29'
down_revision: Union[str, Sequence[str], None] = '5f9e82de5e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Change agenda to JSON and migrate existing text
    op.execute(
        """
        ALTER TABLE study_sessions
        ALTER COLUMN agenda TYPE JSON USING 
        CASE 
            WHEN agenda IS NULL OR agenda = '' THEN NULL
            ELSE ('[{"title": "Legacy Agenda", "duration_minutes": 0, "description": ' || to_json(agenda)::text || ', "activity_type": "learning"}]')::json
        END
        """
    )
    op.add_column('study_sessions', sa.Column('objectives', sa.JSON(), nullable=True))
    op.add_column('study_sessions', sa.Column('expected_outcome', sa.Text(), nullable=True))
    
    session_type_enum = postgresql.ENUM('REVISION', 'LECTURE', 'PRACTICE', 'DISCUSSION', 'EXAM_PREP', 'PROJECT', 'INTERVIEW_PREP', 'OTHER', name='studysessiontype')
    session_type_enum.create(op.get_bind())
    
    op.add_column('study_sessions', sa.Column('session_type', session_type_enum, server_default='OTHER', nullable=False))
    op.add_column('study_sessions', sa.Column('learning_path_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_sessions', 'learning_plan_items', ['learning_path_item_id'], ['id'], ondelete='SET NULL')
    op.add_column('study_sessions', sa.Column('generated_by_ai', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('retrieved_chunk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name='chat_messages_session_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_messages_pkey')
    )
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_messages_id', 'chat_messages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='uk_6dotkott2kjsp8vw4d0m25fb7')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chat_sessions_pkey')
    )
    op.create_index('ix_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index('ix_chat_sessions_id', 'chat_sessions', ['id'], unique=False)
    op.create_index('ix_chat_sessions_group_id', 'chat_sessions', ['group_id'], unique=False)
    # ### end Alembic commands ###
