ALTER TABLE users ADD COLUMN IF NOT EXISTS account_type VARCHAR(20) NOT NULL DEFAULT 'STUDENT';
ALTER TABLE users ADD CONSTRAINT users_account_type_check CHECK (account_type IN ('STUDENT', 'PROFESSIONAL'));
