"""Fail generation jobs whose lease has expired.

Summaries, quizzes and flashcards are generated by in-process BackgroundTasks.
A crash or restart drops those tasks and leaves their rows PENDING/GENERATING
forever. Each job row carries `started_at` (its lease); a job still running
after JOB_LEASE is orphaned, because every generation is bounded well inside it
(one AI call with a 120 s client timeout). Only expired leases are failed, so a
replica that restarts never fails a job another replica is still running.

Checked at startup and whenever a job row is read.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta
from typing import Optional

from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.models.flashcard import FlashcardDeck, FlashcardDeckStatus
from app.models.quiz import Quiz, QuizStatus
from app.models.session import SessionSummary, SummaryStatus

logger = logging.getLogger(__name__)

JOB_LEASE = timedelta(minutes=10)

_JOBS = {
    SessionSummary: SummaryStatus,
    Quiz: QuizStatus,
    FlashcardDeck: FlashcardDeckStatus,
}


def _cutoff(now: Optional[datetime]) -> datetime:
    return (now or datetime.utcnow()) - JOB_LEASE


def expire_stale_jobs(db: Session, now: Optional[datetime] = None) -> int:
    """Fail every in-progress job whose lease has expired. Returns how many changed."""
    cutoff = _cutoff(now)
    total = 0
    for model, status in _JOBS.items():
        total += (
            db.query(model)
            .filter(model.status.in_([status.PENDING, status.GENERATING]))
            .filter(or_(model.started_at.is_(None), model.started_at < cutoff))
            .update({model.status: status.FAILED}, synchronize_session=False)
        )
    db.commit()
    if total:
        logger.warning("Failed %d generation job(s) with an expired lease", total)
    return total


def expire_if_stale(db: Session, job, now: Optional[datetime] = None) -> None:
    """Fail one job row in place if it is in progress and its lease has expired."""
    if job is None:
        return
    status = _JOBS[type(job)]
    if job.status not in (status.PENDING, status.GENERATING):
        return
    cutoff = _cutoff(now)
    if job.started_at is not None and job.started_at >= cutoff:
        return

    changed = (
        db.query(type(job))
        .filter(type(job).id == job.id)
        .filter(type(job).status.in_([status.PENDING, status.GENERATING]))
        .filter(or_(type(job).started_at.is_(None), type(job).started_at < cutoff))
        .update({type(job).status: status.FAILED}, synchronize_session=False)
    )
    db.commit()
    if changed:
        db.refresh(job)
        logger.warning("Failed %s for session %s: lease expired", type(job).__name__, job.session_id)
    else:
        db.refresh(job)
