"""Mark generation jobs that a restart interrupted as FAILED.

Summaries, quizzes and flashcards are generated by in-process BackgroundTasks.
A restart drops those tasks, leaving rows PENDING or GENERATING forever. The
service runs a single worker, so at startup no job can still be running: every
such row is an orphan. FAILED lets the UI offer "Try again".
(With several workers or replicas this needs a durable job queue instead.)
"""

from __future__ import annotations

import logging

from sqlalchemy.orm import Session

from app.models.flashcard import FlashcardDeck, FlashcardDeckStatus
from app.models.quiz import Quiz, QuizStatus
from app.models.session import SessionSummary, SummaryStatus

logger = logging.getLogger(__name__)

_JOBS = (
    (SessionSummary, SummaryStatus),
    (Quiz, QuizStatus),
    (FlashcardDeck, FlashcardDeckStatus),
)


def recover_interrupted_jobs(db: Session) -> int:
    """Set every PENDING/GENERATING job row to FAILED. Returns how many changed."""
    total = 0
    for model, status in _JOBS:
        total += (
            db.query(model)
            .filter(model.status.in_([status.PENDING, status.GENERATING]))
            .update({model.status: status.FAILED}, synchronize_session=False)
        )
    db.commit()
    if total:
        logger.warning("Marked %d interrupted generation job(s) as FAILED", total)
    return total
